"""DB 接続管理とスキーマ初期化モジュール。"""

import os
from contextlib import contextmanager
from typing import Generator

import psycopg
from psycopg.rows import dict_row


def _database_url() -> str:
    database_url = os.getenv("DATABASE_URL")
    if database_url:
        return database_url

    host = os.getenv("POSTGRES_HOST", "127.0.0.1")
    port = os.getenv("POSTGRES_PORT", "5432")
    user = os.getenv("POSTGRES_USER", "postgres")
    password = os.getenv("POSTGRES_PASSWORD", "")
    database = os.getenv("POSTGRES_DATABASE", "warikan_app")
    return f"postgresql://{user}:{password}@{host}:{port}/{database}"


@contextmanager
def db_connection() -> Generator[psycopg.Connection, None, None]:
    conn = psycopg.connect(_database_url(), row_factory=dict_row)
    try:
        yield conn
    finally:
        conn.close()


def ensure_schema() -> None:
    queries = [
        """
        CREATE TABLE IF NOT EXISTS groups (
          group_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          group_name VARCHAR(50) NOT NULL,
          CONSTRAINT uq_group_name UNIQUE (group_name)
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS users (
          group_id INTEGER NOT NULL,
          user_name VARCHAR(50) NOT NULL,
          password_hash VARCHAR(255) NOT NULL,
          PRIMARY KEY (group_id, user_name),
          CONSTRAINT fk_users_group
            FOREIGN KEY (group_id)
            REFERENCES groups(group_id)
            ON DELETE CASCADE
            ON UPDATE CASCADE
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS payments (
          payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          group_id INTEGER NOT NULL,
          paid_by_user_name VARCHAR(50) NOT NULL,
          title VARCHAR(100) NOT NULL,
          amount_total NUMERIC(12,2) NOT NULL,
          currency_code CHAR(3) NOT NULL,
          exchange_rate NUMERIC(10,4) NOT NULL,
          payment_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          CONSTRAINT fk_payments_group
            FOREIGN KEY (group_id)
            REFERENCES groups(group_id)
            ON DELETE CASCADE,
          CONSTRAINT fk_payments_paid_by
            FOREIGN KEY (group_id, paid_by_user_name)
            REFERENCES users(group_id, user_name)
            ON DELETE CASCADE
            ON UPDATE CASCADE
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS payment_splits (
          payment_id INTEGER NOT NULL,
          group_id INTEGER NOT NULL,
          beneficiary_user_name VARCHAR(50) NOT NULL,
          amount NUMERIC(12,2) NOT NULL,
          approved BOOLEAN NOT NULL DEFAULT FALSE,
          PRIMARY KEY (payment_id, beneficiary_user_name),
          CONSTRAINT fk_splits_payment
            FOREIGN KEY (payment_id)
            REFERENCES payments(payment_id)
            ON DELETE CASCADE,
          CONSTRAINT fk_splits_beneficiary
            FOREIGN KEY (group_id, beneficiary_user_name)
            REFERENCES users(group_id, user_name)
            ON DELETE CASCADE
            ON UPDATE CASCADE
        );
        """,
    ]
    with db_connection() as conn:
        with conn.cursor() as cur:
            for q in queries:
                cur.execute(q)
        conn.commit()
