services:
  db:
    image: mysql:8.0
    container_name: warikan-mysql
    env_file: .env

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  api:
    build: 
      context: .
      dockerfile: Dockerfile.local
    
    container_name: warikan-api

    env_file: .env

    environment:
      DATABASE_URL: ${DATABASE_URL}
      MYSQL_HOST: db
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    
    volumes:
      - ./:/app
  
volumes:
  mysql: