FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir poetry

ENV POETRY_VIRTUALENVS_CREATE=false \
    POETRY_NO_INTERACTION=1 \
    PYTHONUNBUFFERED=1

COPY pyproject.toml poetry.lock* /app/
RUN poetry install --no-root

COPY . /app

CMD ["bash", "/app/scripts/entrypoint.local.sh"]